[setup]
packages = ["openjdk17", "python311", "git", "unzip"]

[env]
JAVA_HOME = "/nix/store/ijmqf5nr8p4g3r84nxz6x6sqf5jynm1c-openjdk-17+35"
PATH = "${JAVA_HOME}/bin:${PATH}"

[start]
cmd = "uvicorn main:app --host 0.0.0.0 --port 8080"
