name: Build APK

on:
  workflow_dispatch:
    inputs:
      site_name:
        description: "Domain name (e.g., delshiz)"
        required: true
      website_url:
        description: "Full website URL (e.g., https://delshiz.com)"
        required: true
      brand_color:
        description: "Hex color code (e.g., #FF0000)"
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      SITE_NAME: ${{ github.event.inputs.site_name }}
      WEBSITE_URL: ${{ github.event.inputs.website_url }}
      BRAND_COLOR: ${{ github.event.inputs.brand_color }}
      APP_LABEL: ${{ github.event.inputs.site_name }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Install Pillow
      run: pip install pillow

    - name: Generate icon and splash
      run: python generate_images.py "${{ env.SITE_NAME }}" "${{ env.BRAND_COLOR }}"

    - name: Clone apk-template
      run: git clone --depth 1 https://github.com/jibuolly/apk-template.git

    - name: Ensure drawable folder exists and copy splash
      run: |
        mkdir -p apk-template/app/src/main/res/drawable
        cp output/${{ env.SITE_NAME }}-splash-1280x1920.png apk-template/app/src/main/res/drawable/splash.png

    - name: Copy icon to all mipmap sizes
      run: |
        for d in mdpi hdpi xhdpi xxhdpi xxxhdpi; do
          mkdir -p apk-template/app/src/main/res/mipmap-$d
          cp output/${{ env.SITE_NAME }}-512x512.png apk-template/app/src/main/res/mipmap-$d/ic_launcher.png
        done

    - name: Update package name, label and URL
      run: |
        sed -i "s/package=\"[^\"]*\"/package=\"com.${{ env.SITE_NAME }}.android\"/" apk-template/app/src/main/AndroidManifest.xml
        sed -i "s/package .*;/package com.${{ env.SITE_NAME }}.android;/" apk-template/app/src/main/java/com/wixify/android/MainActivity.java
        sed -i "s|loadUrl(\"[^\"]*\")|loadUrl(\"${{ env.WEBSITE_URL }}\")|" apk-template/app/src/main/java/com/wixify/android/MainActivity.java
        sed -i "s|<string name=\"app_name\">.*</string>|<string name=\"app_name\">${{ env.SITE_NAME^ }}</string>|" apk-template/app/src/main/res/values/strings.xml

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Set execute permission for gradlew
      run: chmod +x apk-template/gradlew

    - name: Build APK
      working-directory: apk-template
      run: ./gradlew assembleDebug

    - name: Upload APK directly as artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.SITE_NAME }}.apk
        path: apk-template/app/build/outputs/apk/debug/app-debug.apk
