name: Build APK

on:
  repository_dispatch:
    types: [build-apk]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      SITE_NAME: ${{ github.event.client_payload.site_name }}
      SITE_URL: ${{ github.event.client_payload.website_url }}

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Clone apk-template
      run: git clone --depth 1 https://github.com/jibuolly/apk-template.git

    - name: Verify project structure
      run: |
        ls -la apk-template/app/src/main/
        ls -la apk-template/app/src/main/java/com/wixify/android/

    - name: Replace package name and WebView URL
      run: |
        sed -i "s/package=\"[^\"]*\"/package=\"com.${SITE_NAME}.android\"/" apk-template/app/src/main/AndroidManifest.xml
        sed -i "s/package .*;/package com.${SITE_NAME}.android;/" apk-template/app/src/main/java/com/wixify/android/MainActivity.java
        sed -i "s|loadUrl(\"[^\"]*\")|loadUrl(\"https://${SITE_URL}\")|" apk-template/app/src/main/java/com/wixify/android/MainActivity.java

    - name: Make gradlew executable
      run: chmod +x apk-template/gradlew

    - name: Build APK
      working-directory: apk-template
      run: ./gradlew assembleDebug

    - name: Rename APK to App Name
      run: |
        APP_LABEL=$(echo "${SITE_NAME}" | awk '{print toupper(substr($0,1,1)) tolower(substr($0,2))}')
        mv apk-template/app/build/outputs/apk/debug/app-debug.apk "${APP_LABEL}.apk"

    - name: Upload APK Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Single-APK
        path: ./*.apk
