name: Build APK

on:
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      SITE_NAME: ${{ github.event.client_payload.site_name }}
      BRAND_COLOR: ${{ github.event.client_payload.brand_color }}

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install Pillow
      run: pip install pillow

    - name: Generate icon and splash images
      run: |
        python generate_images.py "${{ env.SITE_NAME }}" "${{ env.BRAND_COLOR }}"

    - name: Clone apk-template
      run: git clone --depth 1 https://github.com/jibuolly/apk-template.git

    - name: Update package name, URL, and app label
      run: |
        sed -i "s/package=\"[^\"]*\"/package=\"com.${{ env.SITE_NAME }}.android\"/" apk-template/app/src/main/AndroidManifest.xml
        sed -i "s/package .*;/package com.${{ env.SITE_NAME }}.android;/" apk-template/app/src/main/java/com/wixify/android/MainActivity.java
        sed -i "s|loadUrl(\"[^\"]*\")|loadUrl(\"https://${{ env.SITE_NAME }}\")|" apk-template/app/src/main/java/com/wixify/android/MainActivity.java
        sed -i "s|<string name=\"app_name\">.*</string>|<string name=\"app_name\">${{ env.SITE_NAME }}</string>|" apk-template/app/src/main/res/values/strings.xml

    - name: Copy generated images
      run: |
        for d in mdpi hdpi xhdpi xxhdpi xxxhdpi; do
          cp output/${{ env.SITE_NAME }}-512x512.png apk-template/app/src/main/res/mipmap-$d/ic_launcher.png
        done
        cp output/${{ env.SITE_NAME }}-splash-1280x1920.png apk-template/app/src/main/res/drawable/splash.png

    - name: Build APK
      working-directory: apk-template
      run: ./gradlew assembleDebug

    - name: Upload APK Artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.SITE_NAME }}.apk
        path: apk-template/app/build/outputs/apk/debug/app-debug.apk
