name: Build APK

on:
  repository_dispatch:
    types: [build-apk]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      SITE_NAME: ${{ github.event.client_payload.site_name }}

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Clone apk-template
      run: git clone --depth 1 https://github.com/jibuolly/apk-template.git

    - name: Update package name and website URL
      run: |
        sed -i "s/package=\"[^\"]*\"/package=\"com.${{ github.event.client_payload.site_name }}.android\"/" apk-template/app/src/main/AndroidManifest.xml
        sed -i "s/package .*;/package com.${{ github.event.client_payload.site_name }}.android;/" apk-template/app/src/main/java/com/wixify/android/MainActivity.java
        sed -i "s|loadUrl(\"[^\"]*\")|loadUrl(\"https://${{ github.event.client_payload.site_name }}.in\")|" apk-template/app/src/main/java/com/wixify/android/MainActivity.java

    - name: Grant execute permission to Gradle
      run: chmod +x apk-template/gradlew

    - name: Build Debug APK
      working-directory: apk-template
      run: ./gradlew assembleDebug

    - name: Rename APK
      run: |
        APP_NAME=$(echo "${{ env.SITE_NAME }}" | awk '{print toupper(substr($0,1,1)) tolower(substr($0,2))}')
        mv apk-template/app/build/outputs/apk/debug/app-debug.apk "${APP_NAME}.apk"

    - name: Upload APK Artifact
      uses: actions/upload-artifact@v4
      with:
        name: app
        path: "*.apk"
