name: Build APK

on:
  repository_dispatch:
    types: [build-apk]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      SITE_NAME: ${{ github.event.client_payload.site_name }}
      WEBSITE_URL: ${{ github.event.client_payload.website_url }}

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Clone apk-template
      run: git clone --depth 1 https://github.com/jibuolly/apk-template.git

    - name: Update package name, website URL, and app label
      run: |
        sed -i "s/package=\"[^\"]*\"/package=\"com.${{ env.SITE_NAME }}.android\"/" apk-template/app/src/main/AndroidManifest.xml
        sed -i "s/package .*;/package com.${{ env.SITE_NAME }}.android;/" apk-template/app/src/main/java/com/wixify/android/MainActivity.java
        sed -i "s|loadUrl(\"[^\"]*\")|loadUrl(\"${{ env.WEBSITE_URL }}\")|" apk-template/app/src/main/java/com/wixify/android/MainActivity.java
        sed -i "s|<string name=\"app_name\">.*</string>|<string name=\"app_name\">${{ env.SITE_NAME }}</string>|" apk-template/app/src/main/res/values/strings.xml

    - name: Set permissions for Gradle
      run: chmod +x apk-template/gradlew

    - name: Build APK
      working-directory: apk-template
      run: ./gradlew assembleDebug

    - name: Rename APK
      run: |
        APP_NAME=$(echo "${{ env.SITE_NAME }}" | awk '{print tolower($0)}')
        mv apk-template/app/build/outputs/apk/debug/app-debug.apk $APP_NAME.apk

    - name: Upload APK Artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.SITE_NAME }}.apk
        path: ${{ env.SITE_NAME }}.apk
